#!/usr/bin/python

import sys
import subprocess

inserted_mainclass = "edu.msu.cme.rdp.classloader.RDPClassLoader"
class_loader_jar = "/scratch/jars/ClassServer.jar:/scratch/jars/commons-lang.jar"

cmd = ["java"]

args = sys.argv[1:]
classpath_found = False

main_class_index = -1

i = 0
while i < len(args):
	if args[i] == "-jar":
		print "This doesn't work with jars, sorry!"
		sys.exit(1)

	if main_class_index == -1 and args[i][0] != '-':
		main_class_index = i + 1

	if args[i] == "-cp":
		cmd.append(args[i])

		i += 1
		args[i] = args[i] + ":" + class_loader_jar
		classpath_found = True

	cmd.append(args[i])
	i += 1

if main_class_index == -1:
	print "Please specify a main class"
	sys.exit(1)

cmd.insert(main_class_index, inserted_mainclass)
cmd.insert(main_class_index, "-Djava.system.class.loader=%s" % inserted_mainclass)

if not classpath_found:
	cmd.insert(main_class_index, class_loader_jar)
	cmd.insert(main_class_index, "-cp")

subprocess.call(cmd)
